name: "Customizable Docker Buildx"
description: "Configure docker to be used with buildx"
branding:
    icon: archive
    color: blue
inputs:
    tag:
        description: "Tags (comma separated) to apply to the image"
        default: "latest"
    imageName:
        description: "Name of the image"
        required: true
    context:
        description: "The working directory to run build commands from"
        default: "."
    dockerFile:
        description: "Name of the Dockerfile"
        default: "Dockerfile"
    buildArg:
        description: "Build arguments (comma separated) used to build the image"
        default: "none"
    publish:
        description: "Indicate if the builded image should be published on Docker HUB"
        default: "false"
    platform:
        description: "Platforms (comma separated) that should be used to build the image"
        default: "linux/amd64,linux/arm64,linux/arm/v7"
    dockerHubUser:
        description: "User that will publish the image, if indicated"
    dockerHubPassword:
        description: "Password of the dockerHubUser"
    arm64_ssh_key:
        description: "The ssh key to use to connect to the arm host"
    arm64_host:
        description: "The arm64 host"
runs:
    using: 'node12'
    main: index.js
